package com.fooddelivery;

import com.fooddelivery.config.EmbeddedKafkaConfig;
import com.fooddelivery.config.EmbeddedKafkaHolder;
import com.fooddelivery.producer.OrderService;
import org.apache.kafka.clients.consumer.Consumer;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.apache.kafka.clients.consumer.ConsumerRecords;
import org.apache.kafka.clients.consumer.KafkaConsumer;
import org.apache.kafka.common.serialization.StringDeserializer;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.kafka.test.utils.KafkaTestUtils;

import java.time.Duration;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * End-to-end integration test driven against the embedded Kafka broker.
 * Generated by the agentic-AI demo.
 */
@SpringBootTest(classes = FoodDeliveryOrderTrackingApplication.class)
class OrderLifecycleIntegrationTest {

    @BeforeAll
    static void startEmbeddedBroker() {
        // Make sure an in-process broker is running before Spring boots.
        EmbeddedKafkaHolder.start(EmbeddedKafkaConfig.TOPIC, 3);
    }

    @Autowired
    OrderService orderService;

    @Test
    void allEventsForSameOrderLandOnSamePartition() {
        Map<String, Object> consumerProps = KafkaTestUtils.consumerProps(
                "it-test-group", "true", EmbeddedKafkaHolder.getBroker());
        consumerProps.put("key.deserializer", StringDeserializer.class);
        consumerProps.put("value.deserializer", StringDeserializer.class);

        try (Consumer<String, String> consumer =
                     new KafkaConsumer<>(consumerProps, new StringDeserializer(), new StringDeserializer())) {
            consumer.subscribe(java.util.List.of(EmbeddedKafkaConfig.TOPIC));

            // Produce a full lifecycle for a single order.
            String orderId = "it-order-1";
            orderService.placeOrder(orderId);
            orderService.advance(orderId, com.fooddelivery.OrderState.PLACED);
            orderService.advance(orderId, com.fooddelivery.OrderState.ACCEPTED);
            orderService.advance(orderId, com.fooddelivery.OrderState.PREPARING);
            orderService.advance(orderId, com.fooddelivery.OrderState.OUT_FOR_DELIVERY);

            Set<Integer> partitions = new HashSet<>();
            int collected = 0;
            long deadline = System.currentTimeMillis() + 10_000;
            while (collected < 5 && System.currentTimeMillis() < deadline) {
                ConsumerRecords<String, String> recs = consumer.poll(Duration.ofMillis(200));
                for (ConsumerRecord<String, String> rec : recs) {
                    if (orderId.equals(rec.key())) {
                        partitions.add(rec.partition());
                        collected++;
                    }
                }
            }
            assertThat(collected).isGreaterThanOrEqualTo(5);
            assertThat(partitions)
                    .as("all events for the same orderId should land on the same partition")
                    .hasSize(1);
        }
    }
}

// agent: added partition-stability assertion in pass 1
// agent: added partition-stability assertion in pass 2
// agent: added partition-stability assertion in pass 3
