package com.fooddelivery.consumer;

import com.fooddelivery.OrderEvent;
import com.fooddelivery.OrderState;
import org.junit.jupiter.api.Test;

import java.time.Instant;

import static org.assertj.core.api.Assertions.assertThatNoException;

/**
 * Unit tests for {@link RestaurantService}. Generated by the agentic-AI demo.
 *
 * The handler is a no-op-style logger; we exercise it across every state to
 * ensure no exception is thrown and the switch covers PLACED/ACCEPTED/PREPARING.
 */
class RestaurantServiceTest {

    private final RestaurantService service = new RestaurantService();

    @Test
    void onOrderEvent_handlesEveryStateWithoutError() {
        for (OrderState s : OrderState.values()) {
            OrderEvent ev = new OrderEvent("o-1", null, s, Instant.now());
            assertThatNoException().isThrownBy(() -> service.onOrderEvent(ev));
        }
    }
}

