spring:
  application:
    name: food-delivery-order-tracking
  main:
    banner-mode: "off"

app:
  kafka:
    topic: order-events
    partitions: 3
    replication-factor: 1

logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    kafka: WARN
    org.apache.zookeeper: WARN
    state.change.logger: WARN
    com.fooddelivery: INFO

