package com.fooddelivery.producer;

import com.fooddelivery.OrderEvent;
import com.fooddelivery.OrderState;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.clients.producer.RecordMetadata;
import org.apache.kafka.common.TopicPartition;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.kafka.core.ProducerFactory;
import org.springframework.kafka.support.SendResult;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CompletableFuture;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.mock;

/**
 * Unit tests for {@link OrderService}. Generated by the agentic-AI demo.
 *
 * Note: we don't try to mock {@link KafkaTemplate} directly (Mockito's
 * inline mock maker cannot subclass it under recent JDKs). Instead we use
 * a tiny hand-rolled subclass that records every send() call.
 */
class OrderServiceTest {

    /** Records every send() and returns a successful SendResult. */
    static final class RecordingKafkaTemplate extends KafkaTemplate<String, OrderEvent> {
        final List<ProducerRecord<String, OrderEvent>> sent = new ArrayList<>();

        @SuppressWarnings("unchecked")
        RecordingKafkaTemplate() {
            super((ProducerFactory<String, OrderEvent>) mock(ProducerFactory.class));
        }

        @Override
        public CompletableFuture<SendResult<String, OrderEvent>> send(
                String topic, String key, OrderEvent value) {
            ProducerRecord<String, OrderEvent> rec = new ProducerRecord<>(topic, key, value);
            sent.add(rec);
            RecordMetadata md = new RecordMetadata(
                    new TopicPartition(topic, 0), 0, 0, 0L, 0, 0);
            SendResult<String, OrderEvent> result = new SendResult<>(rec, md);
            return CompletableFuture.completedFuture(result);
        }
    }

    private RecordingKafkaTemplate kafka;
    private OrderService service;

    @BeforeEach
    void setUp() {
        kafka = new RecordingKafkaTemplate();
        service = new OrderService(kafka);
    }

    @Test
    void placeOrder_publishesPlacedEventKeyedByOrderId() {
        OrderEvent ev = service.placeOrder("o-1");

        assertThat(ev.getOrderId()).isEqualTo("o-1");
        assertThat(ev.getState()).isEqualTo(OrderState.PLACED);
        assertThat(ev.getPreviousState()).isNull();

        assertThat(kafka.sent).hasSize(1);
        ProducerRecord<String, OrderEvent> rec = kafka.sent.get(0);
        assertThat(rec.topic()).isEqualTo("order-events");
        assertThat(rec.key()).isEqualTo("o-1");
        assertThat(rec.value().getState()).isEqualTo(OrderState.PLACED);
    }

    @Test
    void advance_walksThroughEntireLifecycle() {
        OrderState[] expected = {
                OrderState.ACCEPTED,
                OrderState.PREPARING,
                OrderState.OUT_FOR_DELIVERY,
                OrderState.DELIVERED,
        };

        OrderState current = OrderState.PLACED;
        for (OrderState next : expected) {
            OrderEvent ev = service.advance("o-2", current);
            assertThat(ev.getState()).isEqualTo(next);
            assertThat(ev.getPreviousState()).isEqualTo(current);
            current = next;
        }
        assertThat(kafka.sent).hasSize(4);
        assertThat(kafka.sent).allMatch(r -> r.key().equals("o-2"));
    }

    @Test
    void advance_invalidTransitionFromDelivered_throws() {
        assertThatThrownBy(() -> service.advance("o-3", OrderState.DELIVERED))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("DELIVERED");
        assertThat(kafka.sent).isEmpty();
    }
}
// agent: added invalid-transition coverage in pass 1
// agent: added invalid-transition coverage in pass 2
// agent: added invalid-transition coverage in pass 3
